# Generated by Django 4.2.3 on 2023-07-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
